### ISSUE TITLE
Error while running pack and babel

### ISSUE THREAD

**Issue by stefanos1316** [Rohitkrops/ssr#15]
I am trying to build to web-applications after I have made some changes.
But I get the following error.

`
ERROR in ./src/client.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /home/sgeorgiou/GitHub/ssr_vs_csr/react/src/client.js: Unexpected token (22:8)

  20 |  */
  21 | 
> 22 | hydrate(<Provider store={store} > <App /> </Provider>, document.querySelector('#app'))
     |         ^
  23 | 
    at Parser.raise (/home/sgeorgiou/GitHub/ssr_vs_csr/react/node_modules/@babel/parser/lib/index.js:3939:15)
    at Parser.unexpected (/home/sgeorgiou/GitHub/ssr_vs_csr/react/node_modules/@babel/parser/lib/index.js:5248:16)
    at Parser.parseExprAtom (/home/sgeorgiou/GitHub/ssr_vs_csr/react/node_modules/@babel/parser/lib/index.js:6328:20)
    at Parser.parseExprSubscripts (/home/sgeorgiou/GitHub/ssr_vs_csr/react/node_modules/@babel/parser/lib/index.js:5924:21)
    at Parser.parseMaybeUnary (/home/sgeorgiou/GitHub/ssr_vs_csr/react/node_modules/@babel/parser/lib/index.js:5903:21)
    at Parser.parseExprOps (/home/sgeorgiou/GitHub/ssr_vs_csr/react/node_modules/@babel/parser/lib/index.js:5812:21)
    at Parser.parseMaybeConditional (/home/sgeorgiou/GitHub/ssr_vs_csr/react/node_modules/@babel/parser/lib/index.js:5784:21)
    at Parser.parseMaybeAssign (/home/sgeorgiou/GitHub/ssr_vs_csr/react/node_modules/@babel/parser/lib/index.js:5731:21)
    at Parser.parseExprListItem (/home/sgeorgiou/GitHub/ssr_vs_csr/react/node_modules/@babel/parser/lib/index.js:6995:18)
    at Parser.parseCallExpressionArguments (/home/sgeorgiou/GitHub/ssr_vs_csr/react/node_modules/@babel/parser/lib/index.js:6124:22)
    at Parser.parseSubscript (/home/sgeorgiou/GitHub/ssr_vs_csr/react/node_modules/@babel/parser/lib/index.js:6029:32)
    at Parser.parseSubscripts (/home/sgeorgiou/GitHub/ssr_vs_csr/react/node_modules/@babel/parser/lib/index.js:5944:19)
    at Parser.parseExprSubscripts (/home/sgeorgiou/GitHub/ssr_vs_csr/react/node_modules/@babel/parser/lib/index.js:5934:17)
    at Parser.parseMaybeUnary (/home/sgeorgiou/GitHub/ssr_vs_csr/react/node_modules/@babel/parser/lib/index.js:5903:21)
    at Parser.parseExprOps (/home/sgeorgiou/GitHub/ssr_vs_csr/react/node_modules/@babel/parser/lib/index.js:5812:21)
    at Parser.parseMaybeConditional (/home/sgeorgiou/GitHub/ssr_vs_csr/react/node_modules/@babel/parser/lib/index.js:5784:21)
    at Parser.parseMaybeAssign (/home/sgeorgiou/GitHub/ssr_vs_csr/react/node_modules/@babel/parser/lib/index.js:5731:21)
    at Parser.parseExpression (/home/sgeorgiou/GitHub/ssr_vs_csr/react/node_modules/@babel/parser/lib/index.js:5684:21)
    at Parser.parseStatementContent (/home/sgeorgiou/GitHub/ssr_vs_csr/react/node_modules/@babel/parser/lib/index.js:7259:21)
    at Parser.parseStatement (/home/sgeorgiou/GitHub/ssr_vs_csr/react/node_modules/@babel/parser/lib/index.js:7145:17)
    at Parser.parseBlockOrModuleBlockBody (/home/sgeorgiou/GitHub/ssr_vs_csr/react/node_modules/@babel/parser/lib/index.js:7696:23)
    at Parser.parseBlockBody (/home/sgeorgiou/GitHub/ssr_vs_csr/react/node_modules/@babel/parser/lib/index.js:7683:10)
    at Parser.parseTopLevel (/home/sgeorgiou/GitHub/ssr_vs_csr/react/node_modules/@babel/parser/lib/index.js:7110:10)
    at Parser.parse (/home/sgeorgiou/GitHub/ssr_vs_csr/react/node_modules/@babel/parser/lib/index.js:8510:17)
    at parse (/home/sgeorgiou/GitHub/ssr_vs_csr/react/node_modules/@babel/parser/lib/index.js:10465:38)
    at parser (/home/sgeorgiou/GitHub/ssr_vs_csr/react/node_modules/@babel/core/lib/transformation/normalize-file.js:170:34)
    at normalizeFile (/home/sgeorgiou/GitHub/ssr_vs_csr/react/node_modules/@babel/core/lib/transformation/normalize-file.js:138:11)
    at runSync (/home/sgeorgiou/GitHub/ssr_vs_csr/react/node_modules/@babel/core/lib/transformation/index.js:44:43)
    at runAsync (/home/sgeorgiou/GitHub/ssr_vs_csr/react/node_modules/@babel/core/lib/transformation/index.js:35:14)
    at /home/sgeorgiou/GitHub/ssr_vs_csr/react/node_modules/@babel/core/lib/transform.js:34:34
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! app-cards@1.1.0 pack: `webpack --config webpack.config.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the app-cards@1.1.0 pack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sgeorgiou/.npm/_logs/2020-08-13T19_21_15_829Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! app-cards@1.1.0 build: `npm run pack && npm run babel`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the app-cards@1.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sgeorgiou/.npm/_logs/2020-08-13T19_21_15_843Z-debug.log
`

Note that I am using node version 13.14.
Any idea how to solve this?

**Comment by RibbtDev** [comment]
There is an error in your code ass per the error log.

```
22 | hydrate( , document.querySelector('#app'))
| ^
```

You have not provided a component to render as the first argument in hydrate function. 

Can you share your repo.

**Comment by RibbtDev** [comment]
Closing this issue because of inactivity. 

Reopen this issue if the problem appears again.
