### ISSUE TITLE
app-cards@1.1.0 start: `node index.js`. npm run start not working

### ISSUE THREAD

**Issue by 2hands10fingers** [Rohitkrops/ssr#5]
Hello! I've just freshly downloaded this repo onto my Mac. Mojave. Node v 10.15.0.

I got this error. How can this be fixed? Thanks!

```
> app-cards@1.1.0 start /Users/antonionogueras/ssr
> node index.js

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module './views/template'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/antonionogueras/ssr/index.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! app-cards@1.1.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the app-cards@1.1.0 start script.```

**Comment by RibbtDev** [comment]
@2hands10fingers you have to first run the build command. 

As you can see in repo there is no views directory. Build command creates it and place files in it after some transformation.

**Comment by 2hands10fingers** [comment]
@Rohitkrops Interesting! Okay, that took care of it. Thank you very much.
